### ISSUE TITLE
NPE for java.lang.Thread

### ISSUE THREAD

**Issue by bjkeller** [albertogoffi/toradocu#118]
Running Toradocu over `java.lang.Thread` from OpenJDK 8 get exception
```
Exception in thread "main" java.lang.NullPointerException
        at org.toradocu.translator.JavaElementsCollector.collect(JavaElementsCollector.java:50)
        at org.toradocu.translator.Matcher.subjectMatch(Matcher.java:41)
        at org.toradocu.translator.ConditionTranslator.translatePropositions(ConditionTranslator.java:220)
        at org.toradocu.translator.ConditionTranslator.processTag(ConditionTranslator.java:501)
        at org.toradocu.translator.ConditionTranslator.translate(ConditionTranslator.java:40)
        at org.toradocu.Toradocu.main(Toradocu.java:158)
```

**Comment by bjkeller** [comment]
Also for `java.util.concurrent.ForkJoinWorkerThread`

```
Exception in thread "main" java.lang.NullPointerException
        at org.toradocu.translator.JavaElementsCollector.collect(JavaElementsCollector.java:50)
        at org.toradocu.translator.Matcher.subjectMatch(Matcher.java:41)
        at org.toradocu.translator.ConditionTranslator.translatePropositions(ConditionTranslator.java:220)
        at org.toradocu.translator.ConditionTranslator.processTag(ConditionTranslator.java:501)
        at org.toradocu.translator.ConditionTranslator.translate(ConditionTranslator.java:40)
        at org.toradocu.Toradocu.main(Toradocu.java:158)
```

**Comment by bjkeller** [comment]
And `java.time.chrono.JapaneseEra`

**Comment by albertogoffi** [comment]
None of the NPE reported here are present in refactor branch.
