### ISSUE TITLE
NullPointerException on parser failure

### ISSUE THREAD

**Issue by bjkeller** [albertogoffi/toradocu#55]
Running the `randoop` branch on `org.apache.commons.collections4.IterableUtils` yields the following errors:

```
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify subjects in "the Iterable to search .".
Exception in thread "main" java.lang.NullPointerException
        at org.toradocu.translator.JavaElementsCollector.collect(JavaElementsCollector.java:35)
        at org.toradocu.translator.Matcher.subjectMatch(Matcher.java:36)
        at org.toradocu.translator.ConditionTranslator.translatePropositions(ConditionTranslator.java:203)
        at org.toradocu.translator.ConditionTranslator.processTag(ConditionTranslator.java:410)
        at org.toradocu.translator.ConditionTranslator.translate(ConditionTranslator.java:39)
        at org.toradocu.Toradocu.main(Toradocu.java:145)
```

**Comment by bjkeller** [comment]
The same problem occurs for `org.apache.commons.collections4.IteratorUtils`

```
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = object) in "the single object over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = iterate) in "the single object over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = object) in "the single object over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = iterate) in "the single object over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = iterate) in "the array over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = iterate) in "the array over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = iterate) in "the array over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = iterate) in "the array over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = iterate) in "the array over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = iterate) in "the array over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = iterate) in "the array over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = iterate) in "the array over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = iterate) in "the array over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = iterate) in "the array over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = iterate) in "the array over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = iterate) in "the array over which to iterate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = decorate) in "the iterator to decorate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = returned) in "the maximum number of elements returned by this iterator ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = decorate) in "the iterator to decorate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = returned) in "the maximum number of elements returned by this iterator ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = immutable) in "the iterator to make immutable ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = immutable) in "the iterator to make immutable ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = immutable) in "the iterator to make immutable ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = use) in "the predicate to use as a filter not null ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = use) in "the predicate to use as a filter not null ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify subjects in "offset is negative .".
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = decorate) in "the iterator to decorate ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify subjects in "the first number of elements to skip .".
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify subjects in "the first iterator to interleave .".
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify subjects in "the first iterator to interleave .".
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify subjects in "the third iterator to interleave .".
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify subjects in "the array of iterators to interleave .".
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify subjects in "the class of array to create .".
Exception in thread "main" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at org.toradocu.translator.Proposition.setTranslation(Proposition.java:88)
        at org.toradocu.translator.ConditionTranslator.translatePropositions(ConditionTranslator.java:308)
        at org.toradocu.translator.ConditionTranslator.processTag(ConditionTranslator.java:410)
        at org.toradocu.translator.ConditionTranslator.translate(ConditionTranslator.java:37)
        at org.toradocu.Toradocu.main(Toradocu.java:145)
```
