### ISSUE TITLE
ParserException on "package-info.java" files in Apache Commons Collections

### ISSUE THREAD

**Issue by bjkeller** [albertogoffi/toradocu#59]
Toradocu throws a ParserException on the `package-info.java` files in Apache Commons Collections.
For instance, for `org.apache.commons.collections4.package-info.java` that consists of just
```
package org.apache.commons.collections4;
```
results in
```
com.github.javaparser.ParseException: Encountered unexpected token: "-" "-"
    at line 2, column 53.

Was expecting one of:

    "<"
    "extends"
    "implements"
    "{"
        at com.github.javaparser.ASTParser.generateParseException(ASTParser.java:9791)
        at com.github.javaparser.ASTParser.jj_consume_token(ASTParser.java:9650)
        at com.github.javaparser.ASTParser.ClassOrInterfaceBody(ASTParser.java:858)
        at com.github.javaparser.ASTParser.ClassOrInterfaceDeclaration(ASTParser.java:500)
        at com.github.javaparser.ASTParser.TypeDeclaration(ASTParser.java:421)
        at com.github.javaparser.ASTParser.CompilationUnit(ASTParser.java:217)
        at com.github.javaparser.InstanceJavaParser.parse(InstanceJavaParser.java:92)
        at com.github.javaparser.JavaParser.parse(JavaParser.java:173)
        at org.toradocu.Toradocu.convertConditionsToJava(Toradocu.java:312)
        at org.toradocu.Toradocu.main(Toradocu.java:203)
```

These are not interesting files as input, but Toradocu should do nothing rather than fail.

**Comment by albertogoffi** [comment]
Currently, Toradocu does not fail but prints the error on the standard error and continues the execution. I'm going to modify Toradocu to log the error and avoid to generate an empty condition class.
