### ISSUE TITLE
NullPointerException in master branch executing the test for the class com.google.common.collect.Ordering

### ISSUE THREAD

**Issue by khaeghar** [albertogoffi/toradocu#62]
Running the master branch on ``com.google.common.collect.Ordering``

 gives a NullPointerException

The logout is

``
[main] TRACE org.toradocu.translator.ConditionTranslator - Identifying propositions from: "if the parameters are not mutually comparable under this ordering." in min(T a,T b)
Exception in thread "main" java.lang.NullPointerException
	at org.toradocu.translator.JavaElementsCollector.collect(JavaElementsCollector.java:35)
	at org.toradocu.translator.Matcher.subjectMatch(Matcher.java:36)
	at org.toradocu.translator.ConditionTranslator.translatePropositions(ConditionTranslator.java:239)
	at org.toradocu.translator.ConditionTranslator.translate(ConditionTranslator.java:68)
	at org.toradocu.Toradocu.main(Toradocu.java:137)
``

**Comment by albertogoffi** [comment]
@khaeghar, 

I'm not able to reproduce the bug. The current master version of Toradocu correctly terminates when run on the class `com.google.common.collect.Ordering`. Can you check again if the problem is still there on your system? Can you provide the command you use to run Toradocu?

Thank you.

**Comment by khaeghar** [comment]
I run it again and with the last version it works. I had an old one, sorry. I'll close this D:.
