### ISSUE TITLE
NPE for Apache Commons Math PolynomialLagrangeForm

### ISSUE THREAD

**Issue by bjkeller** [albertogoffi/toradocu#76]
Running Toradocu over `org.apache.commons.math3.analysis.polynomials.PolynomialFunctionLagrangeForm`

 yields

```
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = points) in "interpolating points ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = values) in "function values at interpolating points ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = ascertain) in "when the activated method itself can ascertain that a precondition specified in the API expressed at the level of the activated method has been violated ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = specified) in "when the activated method itself can ascertain that a precondition specified in the API expressed at the level of the activated method has been violated ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = expressed) in "when the activated method itself can ascertain that a precondition specified in the API expressed at the level of the activated method has been violated ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify a predicate (governor = value) in "the function value ."
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify subjects in "the degree of the polynomial .".
[main] WARN org.toradocu.translator.SentenceParser - Unable to identify subjects in "a fresh copy of the coefficients array .".
Exception in thread "main" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at org.toradocu.translator.Proposition.setTranslation(Proposition.java:88)
        at org.toradocu.translator.ConditionTranslator.translatePropositions(ConditionTranslator.java:304)
        at org.toradocu.translator.ConditionTranslator.processTag(ConditionTranslator.java:426)
        at org.toradocu.translator.ConditionTranslator.translate(ConditionTranslator.java:38)
        at org.toradocu.Toradocu.main(Toradocu.java:163)
```

**Comment by bjkeller** [comment]
Also happens for `org.apache.commons.math3.transform.FastCosineTransformer`
