### ISSUE TITLE
NPE for FreeCol class net.sf.freecol.FreeCol

### ISSUE THREAD

**Issue by bjkeller** [albertogoffi/toradocu#80]
Running over `net.sf.freecol.FreeCol` from https://github.com/randoop/FreeCol get the following error:
```
Exception in thread "main" java.lang.NullPointerException
        at org.toradocu.translator.JavaElementsCollector.collect(JavaElementsCollector.java:49)
        at org.toradocu.translator.Matcher.subjectMatch(Matcher.java:36)
        at org.toradocu.translator.ConditionTranslator.translatePropositions(ConditionTranslator.java:204)
        at org.toradocu.translator.ConditionTranslator.processTag(ConditionTranslator.java:429)
        at org.toradocu.translator.ConditionTranslator.translate(ConditionTranslator.java:39)
        at org.toradocu.Toradocu.main(Toradocu.java:163)
```

**Comment by bjkeller** [comment]
Also happens for randoop fork of `plume.BCELUtil`

**Comment by albertogoffi** [comment]
I confirm the error with `plume.BCEUtil` (Plumelib from our test suite).

The error on `net.sf.freecol.FreeCol ` (from our test suite) is different and I opened a specific issue for that (#81).
