### ISSUE TITLE
NoClassDefFoundError on net.sf.freecol.FreeCol

### ISSUE THREAD

**Issue by albertogoffi** [albertogoffi/toradocu#81]
Toradocu execution on `net.sf.freecol.FreeCol` terminates with the following error:

```
java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.toradocu.extractor.DocumentedMethod.getExecutable(DocumentedMethod.java:263)
	at org.toradocu.translator.JavaElementsCollector.collect(JavaElementsCollector.java:47)
	at org.toradocu.translator.Matcher.subjectMatch(Matcher.java:36)
	at org.toradocu.translator.ConditionTranslator.translatePropositions(ConditionTranslator.java:204)
	at org.toradocu.translator.ConditionTranslator.processTag(ConditionTranslator.java:430)
	at org.toradocu.translator.ConditionTranslator.translate(ConditionTranslator.java:39)
	at org.toradocu.Toradocu.main(Toradocu.java:163)
	[...]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
```

This might be related to #79.

**Comment by albertogoffi** [comment]
The problem stems from the fact that Toradocu requires only the binaries of the system under analysis (through the option --class-dir. Those binaries can be incomplete, for example when the system under analysis relies on third-party libraries to implement some of its functionalities. In this case, reflection APIs can throw exception at some point. For an example, look at the following code using the `ParseException` class from [Apache Commons CLI](https://commons.apache.org/cli):
```java
package pkg;

import org.apache.commons.cli.ParseException;

public class AClass {
  public static void main(String[] args) {
    try {
      Class<?> clazz = Class.forName("pkg.AClass");
      clazz.getMethods(); // Throws ClassNotFoundException if ParseException binary is not on the classpath.
      throw new ParseException(""); // To make the ParseException catch block legal.
    } catch (ClassNotFoundException e) {
    } catch (ParseException e) {}
  }
}
```

A possible solution is to require all the binaries (i.e., the system under analysis' classpath).
