### ISSUE TITLE
NPE within doclet

### ISSUE THREAD

**Issue by bjkeller** [albertogoffi/toradocu#85]
This exception occurred when running Toradocu on `com.google.common.util.concurrent.Futures` from `https://github.com/randoop/guava/tree/master/guava`:
```
java.lang.NullPointerException
        at com.sun.tools.javadoc.ClassDocImpl.importedClasses(ClassDocImpl.java:1111)
        at org.toradocu.extractor.JavadocExtractor.getExceptionName(JavadocExtractor.java:236)
        at org.toradocu.extractor.JavadocExtractor.extractThrowsTags(JavadocExtractor.java:325)
        at org.toradocu.extractor.JavadocExtractor.extract(JavadocExtractor.java:68)
        at org.toradocu.Toradocu.process(Toradocu.java:509)
        at org.toradocu.doclet.formats.html.HtmlDoclet.generateClassFiles(HtmlDoclet.java:182)
        at org.toradocu.doclet.internal.toolkit.AbstractDoclet.generateClassFiles(AbstractDoclet.java:192)
        at org.toradocu.doclet.internal.toolkit.AbstractDoclet.startGeneration(AbstractDoclet.java:137)
        at org.toradocu.doclet.internal.toolkit.AbstractDoclet.start(AbstractDoclet.java:82)
        at org.toradocu.doclet.formats.html.HtmlDoclet.start(HtmlDoclet.java:87)
        at org.toradocu.doclet.standard.Standard.start(Standard.java:39)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
        at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
        at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
        at com.sun.tools.javadoc.Start.begin(Start.java:219)
        at com.sun.tools.javadoc.Start.begin(Start.java:205)
        at com.sun.tools.javadoc.Main.execute(Main.java:162)
        at org.toradocu.Toradocu.main(Toradocu.java:102)
```

**Comment by albertogoffi** [comment]
This happens also for `com.google.common.util.concurrent.Futures ` of Guava 19.
